name: DEV
variables:
  - name: ZONTAL_HOST
    value: zontaldev.jnj.com
  - name: client_id
    value: revvity-signals-api
  - secret: true
    name: client_secret
  - secret: true
    name: zontal_access_token
  - name: reccount
    value:
      type: number
      data: "1"
  - name: IPID
    value: 247d49949d9945a8a1ed7bcc5c986c
  - name: IPTitle
    value: 00237_NIR005_G017_water_S0995945_S01.001
